### PR TITLE
Small fixes to make DAG ready for a tag

### PR DESCRIPTION
**Pull request by jlingema**
- Adding more formatting to README
- Fixes in init and CMake for install area and install targets
- Fixing version

### CODE REVIEW

**Comment by jlingema** [comment]
@alicerobson: Could you have a look if you agree with my changes and if the code is in the stage that you'd like to have for a first tag? I see that your master is a few commits ahead of this one, maybe you can do a PR if you think they should be in before I tag here (for a central installation).

**Comment by alicerobson** [comment]
Hi Joschka
So far as I can see all the changes on my master were to create a new README.md file for DAG which I did during our documentation sprint. I think it would be good to include this, although I see you also did some work on the README.txt/.md file.
I don’t seem to be getting an option to do a Pull request and I notice that HEP-FCC/dag is listed as a fork of alicerobson/DAG … What should I do to get make a pull request in this circumstance?
Alice

**Comment by jlingema** [comment]
My bad.. It's already here: #1

**Comment by jlingema** [comment]
I re-based the changes. If you're ok with that, we can also merge this one and create a tag.

**Comment by alicerobson** [comment]
That is fine with me.
A

**Pull request merged**
